## Dataframes for ML

## Data prep

In [2]:
import functions_analysis as func
import pandas as pd
import numpy as np
import pickle
import os

In [2]:
files_names=[
        ['vitaminD_AF/apo','VDR_AF_apo',1,None],
    ['vitaminD_AF/D3','VDR_AF_D3',1,'VDX'],
    ['vitaminD_AF/M9Q','VDR_AF_M9Q',1,'M9Q'],
       ['halm2/apo','halm2_AF_apo',1,None],
    ['halm2/apo','halm2_AF_apo',1,'ATP'],
    ['barnase','barnase_A',3,None],
    ['alpha_lactalbumin','alpha_lactalbumin_apo',2,None],
    ['m_lipin','m_lipin',461,None],
    ['secB','secB',9,None],
  ['alpha_spectrin','alpha_spectrin',1,None],
    ['enolase','enolase_apo',1,None]
]

files_names_Y=[
       ['VDR_AF_apo'],
    ['VDR_AF_D3'],
    ['VDR_AF_M9Q'],
    ['halm2_AF_apo'],
    ['halm2_AF_ATP'],
    ['barnase_A'],
    ['alpha_lactalbumin_apo'],
    ['m_lipin'],
    ['secB'],
    ['alpha_spectrin'],
    ['enolase_apo']

]

In [3]:
Y_values=func.data_extractionY(files_names_Y)  
Y_values

,id,prot,replicate,res_name,res_idx,dG
0,VDR_AF_apo_1_ALA5,VDR_AF_apo,1,ALA,5,3.797433
1,VDR_AF_apo_1_ALA6,VDR_AF_apo,1,ALA,6,3.662275
2,VDR_AF_apo_1_SER7,VDR_AF_apo,1,SER,7,4.187608
3,VDR_AF_apo_1_THR8,VDR_AF_apo,1,THR,8,4.017330
4,VDR_AF_apo_1_SER9,VDR_AF_apo,1,SER,9,4.485349
...,...,...,...,...,...,...
13132,enolase_apo_3_HIS432,enolase_apo,3,HIS,432,8.931507
13133,enolase_apo_3_GLY433,enolase_apo,3,GLY,433,8.909385
13134,enolase_apo_3_ASP434,enolase_apo,3,ASP,434,9.054586
13135,enolase_apo_3_LYS435,enolase_apo,3,LYS,435,8.376636
13136,enolase_apo_3_LEU436,enolase_apo,3,LEU,436,8.375074

In [4]:
data_filtered=func.data_extractionX(files_names)

analysing:  VDR_AF_apo
analysing:  VDR_AF_D3
analysing:  VDR_AF_M9Q
analysing:  halm2_AF_apo
analysing:  halm2_AF_apo
analysing:  barnase_A
analysing:  alpha_lactalbumin_apo
analysing:  m_lipin
analysing:  secB
analysing:  alpha_spectrin
analysing:  enolase_apo

In [6]:
import os
os.chdir('****')
data_filtered.to_csv('all_data_unproc_index_complete.csv',index=False)
Y_values.to_csv('Y_values_unproc_index_complete',index=False)